branches:

  only:
  - master
  - develop
language: python
cache: yarn
python:
  - "3.5"
# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
# command to run tests
script:
  - echo $TRAVIS_COMMIT
  - export FANDOGH_HOST=http://159.69.216.179:8080
  - COLLECT_ERROR=True fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - fandogh namespace active --name=default
  - fandogh image publish --version=$TRAVIS_COMMIT || travis_terminate 1
  - if [ $TRAVIS_BRANCH = 'master' ]; then fandogh service apply -f manifest.yml -p IMAGE_VERSION=$TRAVIS_COMMIT || travis_terminate 1; fi
  - if [ $TRAVIS_BRANCH = 'develop' ]; then fandogh service apply -f staging-manifest.yml -p IMAGE_VERSION=$TRAVIS_COMMIT || travis_terminate 1;  fi
